services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Gabriel123
      POSTGRES_USER: gabriel
      POSTGRES_DB: gabriel_cameras_db

  db-tests:
    image: postgres:16
    restart: always
    ports:
      - 5433:5433
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Gabriel123
      POSTGRES_USER: gabriel
      POSTGRES_DB: gabriel_cameras_db_test
      
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@mateus.com.br
      PGADMIN_DEFAULT_PASSWORD: Teste123
    ports:
      - "5050:80"
    depends_on:
      - db
      - db-tests
